openapi: 3.0.0
info:
  title: NodePop
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/ads/:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-api-add
      description: Get List of Ads
    parameters: []
    post:
      summary: ''
      operationId: post-api-ads
      responses:
        '201':
          description: Created
          content:
            multipart/form-data:
              schema:
                $ref: '#/components/schemas/ad'
      description: Create an ad
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ad'
    patch:
      summary: Upload Ad
      operationId: patch-api-ads
      responses:
        '201':
          description: Created
      parameters: []
      description: Updload ad by _id.
  '/api/ads/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ad'
      operationId: get-api-ads-id
      description: Get an ad by with identifier (_id)
    delete:
      summary: ''
      operationId: delete-api-ads-id
      responses:
        '204':
          description: No Content
      description: Delete an ad with the identifier
components:
  schemas:
    ad:
      title: ad
      type: object
      properties:
        name:
          type: string
        onSale:
          type: boolean
        cost:
          type: number
        imagePath:
          type: string
        tags:
          type: array
          items:
            type: string
        _id:
          type: string
          readOnly: true
      required:
        - name
        - onSale
        - cost
        - imagePath
      x-examples: {}
